
        <section class="rev-slider">
            <div id="rev_slider_275_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="webster-slider-10" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
                <!-- START REVOLUTION SLIDER 5.4.6.3 fullwidth mode -->
                <div id="rev_slider_275_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.6.3">
                    <ul> 
            <?php $index = 1;
                foreach ($banner as $row) { 
                 if (($index%2)!=0) { ?>
                        <!-- SLIDE  -->
                        <li data-index="rs-769" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="7000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                            <!-- MAIN IMAGE -->
                            <img src="uploads/slider/<?php echo $row->imageUpload; ?>" data-bgcolor='#141414' style='background:#141414' alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                            <!-- LAYERS -->
                            <!-- LAYER NR. 1 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-8" data-x="center" data-hoffset="" data-y="320" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":300,"split":"chars","splitdelay":0.05,"speed":1900,"split_direction":"forward","frame":"0","from":"y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5; white-space: nowrap; font-size: 16px; line-height: 22px; font-weight: 400; color: #ffffff; letter-spacing: 10px;font-family:Montserrat;text-transform:uppercase;"><?php echo $row->title; ?>
                            </div>
                            <!-- LAYER NR. 2 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-9" data-x="center" data-hoffset="" data-y="360" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1680,"split":"chars","splitdelay":0.05,"speed":2000,"split_direction":"forward","frame":"0","from":"y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; white-space: nowrap; font-size: 60px; line-height: 62px; font-weight: 600; color: #ffffff; letter-spacing: 0px;font-family:Poppins;"><?php echo $row->tagLine; ?></div>
                            <!-- LAYER NR. 3 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-13" data-x="500" data-y="-20" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 4 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-19" data-x="474" data-y="-39" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 5 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-20" data-x="449" data-y="-58" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 6 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-21" data-x="423" data-y="-78" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 7 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-22" data-x="398" data-y="-98" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 8 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-23" data-x="372" data-y="-117" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 9 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-24" data-x="347" data-y="-137" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 10 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-25" data-x="320" data-y="-157" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 11 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-28" data-x="-370" data-y="-478" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 12 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-29" data-x="-371" data-y="-500" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 16;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 13 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-30" data-x="-371" data-y="-521" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 17;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 14 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-31" data-x="-371" data-y="-544" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 18;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 15 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-32" data-x="-370" data-y="-566" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 19;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 16 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-33" data-x="-370" data-y="-589" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 20;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 17 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-34" data-x="-371" data-y="-613" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 21;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 18 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-35" data-x="-371" data-y="-635" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:54;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 22;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="757px" data-hh="780px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 19 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-36" data-x="1481" data-y="422" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 23;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 20 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-37" data-x="1481" data-y="453" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 24;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 21 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-38" data-x="1480" data-y="483" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 25;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 22 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-39" data-x="1481" data-y="511" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 26;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 23 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-40" data-x="1481" data-y="540" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 27;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 24 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-41" data-x="1481" data-y="569" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 28;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 25 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-42" data-x="1480" data-y="600" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 29;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 26 -->
                            <div class="tp-caption   tp-resizeme" id="slide-769-layer-43" data-x="1480" data-y="629" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":0,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;rZ:234;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 30;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/30f39-1.png" alt="" data-ww="814px" data-hh="839px" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 27 -->
                            <a class="tp-caption rev-btn  tp-resizeme  rev-button" href="<?php echo $row->linkName; ?>" target="_self" id="slide-769-layer-44" data-x="center" data-hoffset="-1" data-y="center" data-voffset="110" data-width="['auto']" data-height="['auto']" data-type="button" data-actions='' data-responsive_offset="on" data-frames='[{"delay":2610,"speed":2000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Power0.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(10,10,10);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 31; white-space: nowrap; font-size: 12px; line-height: 18px; font-weight: 500; color: rgba(255,255,255,1); font-family:Montserrat;text-transform:uppercase;background-color:rgb(132,186,63);border-color:rgba(0,0,0,1);border-radius:3px 3px 3px 3px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;"><?php echo $row->buttonName; ?></a>
                        </li>
            <?php }else{ ?>
                        <!-- SLIDE  -->
                        <li data-index="rs-770" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="" data-delay="9000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                            <!-- MAIN IMAGE -->
                            <img src="uploads/slider/<?php echo $row->imageUpload; ?>" data-bgcolor='#0f1619' style='background:#0f1619' alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                            <!-- LAYERS -->
                            <!-- LAYER NR. 28 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-13" data-x="100" data-y="bottom" data-voffset="" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 5;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 29 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-14" data-x="100" data-y="bottom" data-voffset="60" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 30 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-15" data-x="100" data-y="bottom" data-voffset="120" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 7;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 31 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-16" data-x="100" data-y="bottom" data-voffset="180" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 32 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-18" data-x="100" data-y="bottom" data-voffset="240" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 33 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-19" data-x="100" data-y="bottom" data-voffset="300" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 34 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-20" data-x="100" data-y="bottom" data-voffset="360" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;">
                                <div class="rs-looped rs-wave" data-speed="5" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 35 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-21" data-x="100" data-y="bottom" data-voffset="420" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;">
                                <div class="rs-looped rs-wave" data-speed="6" data-angle="5" data-radius="5px" data-origin="50% 50%"><img src="revolution/assets/slider-10/8f533-1.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            </div>
                            <!-- LAYER NR. 36 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-770-layer-3" data-x="564" data-y="center" data-voffset="-99" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1500,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13; white-space: nowrap; font-size: 70px; line-height: 62px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">Best </div>
                            <!-- LAYER NR. 37 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-770-layer-6" data-x="center" data-hoffset="340" data-y="center" data-voffset="-100" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1500,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14; white-space: nowrap; font-size: 70px; line-height: 62px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">your </div>
                            <!-- LAYER NR. 38 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-770-layer-8" data-x="center" data-hoffset="-351" data-y="370" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2600,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15; white-space: nowrap; font-size: 70px; line-height: 72px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">Small </div>
                            <!-- LAYER NR. 39 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-770-layer-10" data-x="center" data-hoffset="418" data-y="center" data-voffset="-24" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2600,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 16; white-space: nowrap; font-size: 70px; line-height: 72px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">webster </div>
                            <!-- LAYER NR. 40 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-5" data-x="center" data-hoffset="87" data-y="bottom" data-voffset="-1" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":300,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 17;"><img src="revolution/assets/slider-10/1bf51-Man.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            <!-- LAYER NR. 41 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-770-layer-4" data-x="center" data-hoffset="" data-y="center" data-voffset="-100" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":1500,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 18; white-space: nowrap; font-size: 70px; line-height: 62px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">way to grow </div>
                            <!-- LAYER NR. 42 -->
                            <div class="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-770-layer-9" data-x="center" data-hoffset="8" data-y="center" data-voffset="-24" data-width="['auto']" data-height="['auto']" data-type="text" data-responsive_offset="on" data-frames='[{"delay":2600,"speed":2000,"frame":"0","from":"y:-50px;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 19; white-space: nowrap; font-size: 70px; line-height: 72px; font-weight: 500; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;">business with </div>
                            <!-- LAYER NR. 43 -->
                            <div class="tp-caption   tp-resizeme" id="slide-770-layer-24" data-x="center" data-hoffset="" data-y="center" data-voffset="70" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-type="image" data-responsive_offset="on" data-frames='[{"delay":3530,"speed":2000,"frame":"0","from":"z:0;rX:0deg;rY:0;rZ:0;sX:2;sY:2;skX:0;skY:0;opacity:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 20;"><img src="revolution/assets/slider-10/208a5-border2.png" alt="" data-ww="auto" data-hh="auto" data-no-retina> </div>
                            <!-- LAYER NR. 44 -->
                            <a class="tp-caption rev-btn  tp-resizeme  rev-button" href="<?php echo $row->linkName; ?>" target="_self" id="slide-770-layer-22" data-x="center" data-hoffset="-90" data-y="center" data-voffset="150" data-width="['auto']" data-height="['auto']" data-type="button" data-actions='' data-responsive_offset="on" data-frames='[{"delay":3910,"speed":2000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Power0.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgb(255,255,255);bg:rgb(10,10,10);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style="z-index: 21; white-space: nowrap; font-size: 12px; line-height: 18px; font-weight: 500; color: rgba(255,255,255,1); font-family:Montserrat;text-transform:uppercase;background-color:rgb(132,186,63);border-color:rgba(0,0,0,1);border-radius:3px 3px 3px 3px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;"><?php echo $row->buttonName; ?></a>
                            <!-- LAYER NR. 45 -->
                            <a class="tp-caption rev-btn  tp-resizeme" href="<?php echo $row->linkName; ?>" target="_self" id="slide-770-layer-23" data-x="center" data-hoffset="90" data-y="center" data-voffset="150" data-width="['auto']" data-height="['auto']" data-type="button" data-actions='' data-responsive_offset="on" data-frames='[{"delay":4190,"speed":2000,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"300","ease":"Power0.easeInOut","to":"o:1;rX:0;rY:0;rZ:0;z:0;","style":"c:rgba(0,0,0,1);bg:rgba(255,255,255,1);"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[30,30,30,30]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[30,30,30,30]" style="z-index: 22; white-space: nowrap; font-size: 12px; line-height: 16px; font-weight: 500; color: rgba(255,255,255,1); font-family:Montserrat;text-transform:uppercase;background-color:rgba(0,0,0,0);border-color:rgb(255,255,255);border-style:solid;border-width:2px 2px 2px 2px;border-radius:3px 3px 3px 3px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none;"><?php echo $row->buttonName; ?></a>
                        </li>
            <?php }
              $index++;} ?>
                    </ul>
                    <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
                </div>
            </div>
        </section>